// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: api.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IdempotencyService_CheckKey_FullMethodName   = "/api.IdempotencyService/CheckKey"
	IdempotencyService_ConfirmKey_FullMethodName = "/api.IdempotencyService/ConfirmKey"
)

// IdempotencyServiceClient is the client API for IdempotencyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Описание сервиса и его методов
type IdempotencyServiceClient interface {
	CheckKey(ctx context.Context, in *CheckKeyRequest, opts ...grpc.CallOption) (*CheckKeyResponse, error)
	ConfirmKey(ctx context.Context, in *ConfirmKeyRequest, opts ...grpc.CallOption) (*ConfirmKeyResponse, error)
}

type idempotencyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIdempotencyServiceClient(cc grpc.ClientConnInterface) IdempotencyServiceClient {
	return &idempotencyServiceClient{cc}
}

func (c *idempotencyServiceClient) CheckKey(ctx context.Context, in *CheckKeyRequest, opts ...grpc.CallOption) (*CheckKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckKeyResponse)
	err := c.cc.Invoke(ctx, IdempotencyService_CheckKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *idempotencyServiceClient) ConfirmKey(ctx context.Context, in *ConfirmKeyRequest, opts ...grpc.CallOption) (*ConfirmKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmKeyResponse)
	err := c.cc.Invoke(ctx, IdempotencyService_ConfirmKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdempotencyServiceServer is the server API for IdempotencyService service.
// All implementations must embed UnimplementedIdempotencyServiceServer
// for forward compatibility.
//
// Описание сервиса и его методов
type IdempotencyServiceServer interface {
	CheckKey(context.Context, *CheckKeyRequest) (*CheckKeyResponse, error)
	ConfirmKey(context.Context, *ConfirmKeyRequest) (*ConfirmKeyResponse, error)
	mustEmbedUnimplementedIdempotencyServiceServer()
}

// UnimplementedIdempotencyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdempotencyServiceServer struct{}

func (UnimplementedIdempotencyServiceServer) CheckKey(context.Context, *CheckKeyRequest) (*CheckKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckKey not implemented")
}
func (UnimplementedIdempotencyServiceServer) ConfirmKey(context.Context, *ConfirmKeyRequest) (*ConfirmKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmKey not implemented")
}
func (UnimplementedIdempotencyServiceServer) mustEmbedUnimplementedIdempotencyServiceServer() {}
func (UnimplementedIdempotencyServiceServer) testEmbeddedByValue()                            {}

// UnsafeIdempotencyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdempotencyServiceServer will
// result in compilation errors.
type UnsafeIdempotencyServiceServer interface {
	mustEmbedUnimplementedIdempotencyServiceServer()
}

func RegisterIdempotencyServiceServer(s grpc.ServiceRegistrar, srv IdempotencyServiceServer) {
	// If the following call panics, it indicates UnimplementedIdempotencyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IdempotencyService_ServiceDesc, srv)
}

func _IdempotencyService_CheckKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdempotencyServiceServer).CheckKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdempotencyService_CheckKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdempotencyServiceServer).CheckKey(ctx, req.(*CheckKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdempotencyService_ConfirmKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdempotencyServiceServer).ConfirmKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdempotencyService_ConfirmKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdempotencyServiceServer).ConfirmKey(ctx, req.(*ConfirmKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdempotencyService_ServiceDesc is the grpc.ServiceDesc for IdempotencyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdempotencyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.IdempotencyService",
	HandlerType: (*IdempotencyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckKey",
			Handler:    _IdempotencyService_CheckKey_Handler,
		},
		{
			MethodName: "ConfirmKey",
			Handler:    _IdempotencyService_ConfirmKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
